### ISSUE TITLE
Add: Option to output 'to' and 'headers' as JSON objects in addition to arrays

### ISSUE THREAD

**Issue by pataquets** [SpamScope/mail-parser#20]
I need it for another use case and would like to get feedback before working on it.
Not sure how to implement it. Things coming to mind:
* A separate set of ```_obj()``` terminated properties?
* How to choose from command line?
* Replace the array thingy? I don't think so/not sure, unless...
* ...it's useful for adding additional fields, for diagnostic or other infos on each individual element.
* Other thoughts?

**Comment by fedelemantuano** [comment]
I'm working on it. There will 3 types of properties:

 - `name` will always be object. The name is the official RFC name.
 - `name_json` will always be JSON.
 - `name_raw` will always return raw data from mail.

These changes will not be back compatibility.

From command line you will have only json and not object, because the cli doesn't understand Python object.

What does it mean?
...it's useful for adding additional fields, for diagnostic or other infos on each individual element.

**Comment by pataquets** [comment]
That's great! If I understood correctly, the command's JSON output will be an array of objects like the attachments are, which is fine.

**Comment by fedelemantuano** [comment]
I solved this issue with [this commit](https://github.com/SpamScope/mail-parser/commit/c0d262096b49523adbb4e9bce446fad43b067504).
