### ISSUE TITLE
Parsing of invalid To headers

### ISSUE THREAD

**Issue by sylencecc** [SpamScope/mail-parser#85]
My spamtrap recently collected a few mails of the following form. What sticks out is the header `To: [to]`, which is parsed by mail-parser into `'to_domains': ['', 'to'], 'to': [('', ''), ('', 'to'), ('', '')]`. I'm not sure what the best interpretation should be, maybe treat the invalid mail address (without an `@` char) just as display name and parse it as `'to_domains': [], 'to': [('[to]', '')]` or ignore it entirely?

```
Delivered-To: asdf@example.com\nReceived: from 52.174.0.50 ([52.174.0.50])\n\tby example.com with ESMTP id
2b91306f64655c937a47755ea3036243@example.com;\n\tWed, 23 Dec 2020 10:36:24 +0000\n
Content-Type: multipart/mixed; boundary=\"===============1339923393==\"\nMIME-Version: 1.0\n
From: LIDL <notification@markt.de>\n
To: [to]\nsubject: =?utf-8?q?Herzliche_Gl=C3=BCckw=C3=BCnsche_!_Ihr_Geschenk_ist_verf=C3=BCgbar_=F0=9F=8E=81?=\n
Message-ID: EC2-Of7RkUhCy4J3mla5Q11DF@AWS-MAIL.COM\n\n--===============1339923393==\n
Content-Type: text/html; charset=\"us-ascii\"\nMIME-Version: 1.0\nContent-Transfer-Encoding: 7bit\n\n
<html><head><meta charset=\"utf-8\"/></head>\n <center>\n <br/>\n <p align=\"center\">
<a href=\"https://laudypauty.com/1008f26915e35d4b800/\">
<img alt=\"\" src=\"https://i.ibb.co/cbXFzWT/lidl-de.jpg\"/></a></p>\n
<br/>\n </center></html>\n--===============1339923393==--\n
```

**Comment by fedelemantuano** [comment]
Can I have an complete example?

**Comment by sylencecc** [comment]
I created a [gist](https://gist.github.com/sylencecc/381ea6ae4ed743598fd903d5a837e0f2) with the raw message from above.
Trying to parse that leads to:
```
>>> p = mailparser.parse_from_file('/tmp/raw')
>>> p.to
[('', ''), ('', 'to'), ('', '')]
>> p.to_domains
['', 'to']
```

**Comment by fedelemantuano** [comment]
Hi @sylencecc but I can't manage this issue in mailparser because it's not an issue.
You have an anomaly mail maybe from a spamtrap and someone use malformed header to bypass some controls.

I tested your email and I have these results:

```
LIDL <notification@markt.de>,<class 'str'>, [('LIDL', 'notification@markt.de')]
``` 

A standard field that it's parsed in label and mail. The second step come from standard Python library `email.utils.getaddresses`.

Then I have this case:

```
asdf@example.com,<class 'str'>, [('', 'asdf@example.com')]
```

Only email without label. So you can see the correct parsing.

In your case you have an anomaly field:

```
[to],<class 'str'>, [('', ''), ('', 'to'), ('', '')]
```

Is it label or email? For me this mail must be marked it's anomaly and you should analyze it manually.
So you should manage these cases externally.

I'm sorry but I should close this issue.
